"use client";
import React, { useEffect, useState } from "react";
import DecesTable from "../../components/screen/decesTable";

const Deces = () => {
    const [data, setData] = useState([]);

    const fetchData = async () => {
        try {
            const response = await fetch("/api/deces");
            if (!response.ok) {
                throw new Error("Failed to fetch data");
            }
            const result = await response.json();
            // Handle both Laravel Resource (wrapped in data) and simple array
            setData(Array.isArray(result) ? result : result.data || []);
        } catch (error) {
            console.error("Error fetching data:", error);
        }
    };

    useEffect(() => {
        fetchData();
    }, []);

    const handleAdd = async (newItem) => {
        try {
            // Remove the temporary ID generated by the UI
            const { id, ...payload } = newItem;

            const response = await fetch("/api/deces", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                },
                body: JSON.stringify(payload),
            });

            if (!response.ok) {
                const errorData = await response.json().catch(() => ({}));
                console.error("Error adding data:", errorData);
                return;
            }

            const createdItem = await response.json();
            // Add the created item (with real ID from DB) to state
            setData((prev) => [createdItem.data || createdItem, ...prev]);
        } catch (error) {
            console.error("Error adding data:", error);
        }
    };

    const handleUpdate = async (updatedItem) => {
        try {
            const response = await fetch(`/api/deces/${updatedItem.id}`, {
                method: "PUT",
                headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                },
                body: JSON.stringify(updatedItem),
            });

            if (!response.ok) {
                console.error("Error updating data");
                return;
            }

            const result = await response.json();
            const savedItem = result.data || result;

            setData((prev) =>
                prev.map((item) =>
                    item.id === savedItem.id ? savedItem : item,
                ),
            );
        } catch (error) {
            console.error("Error updating data:", error);
        }
    };

    const handleDelete = async (id) => {
        try {
            const response = await fetch(`/api/deces/${id}`, {
                method: "DELETE",
                headers: {
                    Accept: "application/json",
                },
            });

            if (!response.ok) {
                console.error("Error deleting data");
                return;
            }

            setData((prev) => prev.filter((item) => item.id !== id));
        } catch (error) {
            console.error("Error deleting data:", error);
        }
    };

    return (
        <DecesTable
            data={data}
            onAdd={handleAdd}
            onUpdate={handleUpdate}
            onDelete={handleDelete}
        />
    );
};
export default Deces;
